version: '3'
services:
  flannel:
    image: flannel:0.25.5
    build: ./
    network_mode: host
    privileged: true
    environment:
      - ETCD_ENDPOINTS=http://192.168.5.40:2379  # etcd 
      - IFACE=ens32                              # 實體網卡
      - FLANNEL_NETWORK=10.0.0.0/8           
      - FLANNEL_SUBNETLEN=24
    volumes:
      - ./subnet-file:/run/flannel
      - /dev/net:/dev/net
    restart: always
