version: '3'
services:
  flannel:
    image: flannel:0.25.5
    build: ./
    network_mode: host
    privileged: true
    environment:
      - ETCD_ENDPOINTS=http://192.168.5.40:2379  # etcd 
      - IFACE=ens32                              # 實體網卡
    volumes:
      - ./config/run-flannel:/run/flannel
      - ./config/etc-flannel:/etc/flannel
      - /dev/net:/dev/net
    restart: always
