version: '3'
services:
  flannel:
    image: flannel:0.25.5
    build: ./
    network_mode: host
    privileged: true
    environment:
      - ETCD_ENDPOINTS=http://192.168.5.40:2379  # etcd 
      - IFACE=ens32                              # 實體網卡
    volumes:
      - ./subnet-file:/run/flannel
      - /dev/net:/dev/net
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
